base_config:
  cuda_visible_devices: 0
  data_path: ./data/processed_data/junyi/junyi_processed.csv
  max_length: 200
  max_episodes: 5000
  wandb_project: EduRec-RL-Experiments-V0712
  wandb_tags: ["HRL", "ALL_JunyiDataset"]
  use_wandb: false
  agent: HRL
  eval_interval: 1
  exp_name: revise-s20-g10
  runs: 3                   
  n_step: false
  graph_path: ./data/processed_data/junyi/prerequest_graph.gexf
  graph_embedding_path: ./data/processed_data/junyi/GraphEmbeddings.npy            

rct-5:
  learning_pattern: rct
  max_steps: 5
  num_goals: 500
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2  
    ppo_epochs: 4  
    mini_batch_size: 4 
    max_sub_step: 5
    emb_cons_num: 10
    candidates_method: embedding 

rct-10:
  learning_pattern: rct
  max_steps: 10
  num_goals: 500
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2  
    ppo_epochs: 4  
    mini_batch_size: 4 
    max_sub_step: 5
    emb_cons_num: 10
    candidates_method: embedding 

rct-20:
  learning_pattern: rct
  max_steps: 20
  num_goals: 500
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2  
    ppo_epochs: 4  
    mini_batch_size: 4 
    max_sub_step: 5
    emb_cons_num: 10
    candidates_method: embedding 

revise-s10-g10:
  learning_pattern: revise
  max_steps: 10
  num_goals: 10
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2       
    ppo_epochs: 4           
    mini_batch_size: 8   
    max_sub_step: 5         
    emb_cons_num: 10        
    candidates_method: embedding

revise-s20-g10:
  learning_pattern: revise
  max_steps: 20
  num_goals: 10
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2       
    ppo_epochs: 4           
    mini_batch_size: 8   
    max_sub_step: 5         
    emb_cons_num: 10        
    candidates_method: embedding

revise-s30-g10:
  learning_pattern: revise
  max_steps: 30
  num_goals: 10
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2       
    ppo_epochs: 4           
    mini_batch_size: 8   
    max_sub_step: 5         
    emb_cons_num: 10        
    candidates_method: embedding

learn-s10-g10:
  learning_pattern: learn
  max_steps: 10
  num_goals: 10
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2       
    ppo_epochs: 4           
    mini_batch_size: 8   
    max_sub_step: 5         
    emb_cons_num: 10        
    candidates_method: embedding

learn-s20-g10:
  learning_pattern: learn
  max_steps: 20
  num_goals: 10
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2       
    ppo_epochs: 4           
    mini_batch_size: 8   
    max_sub_step: 5         
    emb_cons_num: 10        
    candidates_method: embedding

learn-s30-g10:
  learning_pattern: learn
  max_steps: 30
  num_goals: 10
  agent_config:
    hidden_dim: 300         
    gamma: 0.98  
    lr: 0.00003             
    clip_epsilon: 0.2       
    ppo_epochs: 4           
    mini_batch_size: 8   
    max_sub_step: 5         
    emb_cons_num: 10        
    candidates_method: embedding