cuda_visible_devices: 5

dataset_name:  junyi 

model_name: UniLPR

seed: 42

train:
  num_negative: 0
  num_epochs: 50
  learning_rate: 0.0005
  patience: 5
  model_save_path: "./saved_models"
  

dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: True

dataset:
  max_length: 200

model:
  hidden_size: 256
  emb_dim: 256
  dropout: 0.02
  num_layers: 4
  max_len: 200
