
base_config:
  cuda_visible_devices: 0
  data_path: ./data/processed_data/assist09/assist09_processed.csv
  max_length: 200
  max_episodes: 5000
  wandb_project: EduRec-RL-Experiments-V0712
  wandb_tags: ["Random", "assist09"]
  use_wandb: false
  agent: Random
  eval_interval: 1
  exp_name: rct-10 
  runs: 1

rct-5:
  learning_pattern: rct
  n_step: false
  max_steps: 5
  num_goals: 500
  agent_config:
    hidden_dim: 128
    lr: 0.00003

rct-10:
  learning_pattern: rct
  n_step: false
  max_steps: 10
  num_goals: 500
  agent_config:
    hidden_dim: 128
    lr: 0.00003

rct-20:
  learning_pattern: rct
  n_step: false
  max_steps: 20
  num_goals: 500
  agent_config:
    hidden_dim: 128
    lr: 0.00003

learn-s10-g10:
  learning_pattern: learn
  n_step: false
  max_steps: 10
  num_goals: 10
  agent_config:
    hidden_dim: 128
    lr: 0.00003

learn-s20-g10:
  learning_pattern: learn
  n_step: false
  max_steps: 20
  num_goals: 10
  agent_config:
    hidden_dim: 128
    lr: 0.00003

learn-s30-g10:
  learning_pattern: learn
  n_step: false
  max_steps: 30
  num_goals: 10
  agent_config:
    hidden_dim: 128
    lr: 0.00003

revise-s10-g10:
  learning_pattern: revise
  n_step: false
  max_steps: 10
  num_goals: 10
  agent_config:
    hidden_dim: 128
    lr: 0.00003

revise-s20-g10:
  learning_pattern: revise
  n_step: false
  max_steps: 20
  num_goals: 10
  agent_config:
    hidden_dim: 128
    lr: 0.00003


revise-s30-g10:
  learning_pattern: revise
  n_step: false
  max_steps: 30
  num_goals: 10
  agent_config:
    hidden_dim: 128
    lr: 0.00003