base_config:
  cuda_visible_devices: 0
  data_path: ./data/processed_data/assist09/assist09_processed.csv
  max_length: 200
  max_episodes: 5000
  eval_interval: 1
  n_step: false
  wandb_project: EduRec-RL-Experiments-V0709
  wandb_tags: ["UniLPR_PPO", "assist09"]
  use_wandb: false
  agent: UniLPR_PPO
  runs: 1                   
  exp_name: rct-10-AC    

rct-10-AC: 
  learning_pattern: rct
  max_steps: 10
  num_goals: 500
  agent_config:
    strategy: AC            
    hidden_dim: 128         
    gamma: 0.98             
    lr: 0.00008             
    clip_epsilon: 0.2       
    po_epochs: 4           
    mini_batch_size: 16      
    group_size: 10           
    beta: 0.1               
    add_goal: true          
    kt_predict: true       
    seq_predict: true      
    kt_beta: 0.1           
    seq_beta: 0.1            

rct-10-PPO:
  learning_pattern: rct
  max_steps: 10
  num_goals: 500
  agent_config:
    strategy: PPO            
    hidden_dim: 128         
    gamma: 0.98             
    lr: 0.00008             
    clip_epsilon: 0.2       
    po_epochs: 4           
    mini_batch_size: 16      
    group_size: 10           
    beta: 0.1               
    add_goal: true          
    kt_predict: true       
    seq_predict: true      
    kt_beta: 0.1            
    seq_beta: 0.1            

learn-s20-g10-AC:
  learning_pattern: learn
  max_steps: 20
  num_goals: 10
  agent_config:
    strategy: AC            
    hidden_dim: 128         
    gamma: 0.98             
    lr: 0.00008             
    clip_epsilon: 0.2       
    po_epochs: 4           
    mini_batch_size: 16      
    group_size: 10           
    beta: 0.1               
    add_goal: true          
    kt_predict: true       
    seq_predict: true      
    kt_beta: 0.01            
    seq_beta: 0.01            

learn-s20-g10-PPO:
  learning_pattern: learn
  max_steps: 20
  num_goals: 10
  agent_config:
    strategy: PPO            
    hidden_dim: 128         
    gamma: 0.98             
    lr: 0.00008             
    clip_epsilon: 0.2       
    po_epochs: 4           
    mini_batch_size: 16      
    group_size: 10           
    beta: 0.1               
    add_goal: true          
    kt_predict: true       
    seq_predict: true      
    kt_beta: 0.1            
    seq_beta: 0.1            

revise-s20-g10-AC:
  learning_pattern: revise
  max_steps: 20
  num_goals: 10
  agent_config:
    strategy: AC            
    hidden_dim: 128         
    gamma: 0.98             
    lr: 0.00008             
    clip_epsilon: 0.2       
    po_epochs: 4           
    mini_batch_size: 16      
    group_size: 10           
    beta: 0.1               
    add_goal: true          
    kt_predict: true       
    seq_predict: true      
    kt_beta: 0.1            
    seq_beta: 0.1            


revise-s20-g10-PPO:
  learning_pattern: revise
  max_steps: 20
  num_goals: 10
  agent_config:
    strategy: PPO            
    hidden_dim: 128         
    gamma: 0.98             
    lr: 0.00008             
    clip_epsilon: 0.2       
    po_epochs: 4           
    mini_batch_size: 16      
    group_size: 10           
    beta: 0.1               
    add_goal: true          
    kt_predict: true       
    seq_predict: true      
    kt_beta: 0.1            
    seq_beta: 0.1            